version: '4'

services:
  ibn_front:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: ibn_front
    restart: unless-stopped
    ports:
      - "3000:3000"
