version: '3'

services:
  ibn_front:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: ibn_front
    restart: unless-stopped

    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - ibn_front
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - dhparam:/etc/ssl/certs/
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email enoquebelmiro@hotmail.com --agree-tos --no-eff-email --force-renewal -d sejaibn.org.br  -d www.sejaibn.org.br

volumes:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/site_ibn/dhparam
      o: bind

  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /var/www/IBN_Front
      o: bind

networks:
  app-network:
    driver: bridge
